version: '2'
services:
    elasticsearch:
        image: elasticsearch
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=testpass
    operacat:
        build:
            context: .
            args:
                OPERACAT_SECRET_KEY: "superdupersecret"
                OPERACAT_BASE_URL: "/"
                ELASTIC_SEARCH_ADDRESS: "elasticsearch:9200"
        ports:
            - "8000:8000"
        depends_on:
            - elasticsearch
            - postgres
